version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      # Mount DB for persistence (optional)
      - django_data:/app/backend/db.sqlite3
    environment:
      - DEBUG=False
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  django_data:
